### ISSUE TITLE
SAIN editor became upside down

### ISSUE THREAD

**Issue by YuqiHuai** [SAIN-Project/Frontend#20]
<img width="1389" alt="Screen Shot 2021-03-09 at 12 26 55 PM" src="https://user-images.githubusercontent.com/34195403/110419380-2e1ce600-80d4-11eb-8314-bfb32a8d0f75.png">

SAIN editor became up-side-down.

I am not sure what I did exactly, I zoomed out and then zoomed in before the issue occurred. The buttons on the top for zoom-in/ zoom-out also became reversed.

**Comment by Ibrahimvse** [comment]
I never had this issue!! please write the exact steps that you did and get this issue!!

**Comment by YuqiHuai** [comment]
I was able to reproduce the issue.

1. Drag any component into the editor
2. Zoom in using the mouse wheel until the component disappears
3. Zoom out and try to find the component added in step 1, it is reversed.

**Comment by jgarci40** [comment]
Thanks, @YuqiHuai! I can replicate the issue, as shown below.

![Screen Shot 2021-03-13 at 8 09 47 PM](https://user-images.githubusercontent.com/8866794/111057019-fc3fb280-8438-11eb-9413-4bab807786d7.png)


@Ibrahimvse @khoiminhpham Could you please look into this and see if you can fix it? I'm not sure if you have higher priority issues to resolve first.

**Comment by Ibrahimvse** [comment]
fixed

**Comment by Sanshin-SF** [comment]
The issue may not have been fixed yet.
I was able to replicate the issue above in another way.

https://user-images.githubusercontent.com/76271316/128777712-6dfb498b-82e3-4a57-8207-5972e765fab1.mp4

1. zoom in using mouse wheel
2. zoom out using mouse wheel
3. zoom out using the zoom slider on the top right

**Comment by jgarci40** [comment]
@Ibrahimvse, could you please look into this again?

**Comment by TarandeepSingh562** [comment]
Update: The bug seems to still happen when using the mouse wheel with the zoom slider. The SAIN editor does not seem to flip when only using mouse wheel to zoom in and out. This bug only seems to happen when both mouse wheel and zoom slider actions are applied.
![image](https://user-images.githubusercontent.com/85138366/134374870-c776ce4a-11ee-4029-80db-a565c4708ad1.png)

**Comment by jgarci40** [comment]
Hi @Ibrahimvse. Just want to make sure you get @TarandeepSingh562's update about this, so I'm tagging you.

**Comment by Sanshin-SF** [comment]
I think this is causing the UI to flip.

The value for "scale" determines the scale of the UI we see.
The zoom slider simply adds or substracts 0.1 to this value max.
and the mouse wheel adds or substracts (current scale * 0.1) to this value.

When we zoom out with our mouse to lower the zoom scale and slide the zoom slider to zoom out, the "scale" value goes to a negative value which causes the UI to flip.

https://user-images.githubusercontent.com/76271316/147146547-08c3e0e6-4399-451d-b357-f2e05b7f6912.mp4

The "scale" value can be examined by ctrl+f ing "scale" in the html.

**Comment by TarandeepSingh562** [comment]
> I think this is causing the UI to flip.
> 
> The value for "scale" determines the scale of the UI we see. The zoom slider simply adds or substracts 0.1 to this value max. and the mouse wheel adds or substracts (current scale * 0.1) to this value.
> 
> When we zoom out with our mouse to lower the zoom scale and slide the zoom slider to zoom out, the "scale" value goes to a negative value which causes the UI to flip.
> 
>  Untitled.mp4 
> The "scale" value can be examined by ctrl+f ing "scale" in the html.

I'm having the same problem after zooming in/out; it seems to randomly flip the interface.
![image](https://user-images.githubusercontent.com/85138366/154162322-e3e0930c-a1d3-4ff6-8872-ef023b501aeb.png)

**Comment by jgarci40** [comment]
@Ibrahimvse @khoiminhpham Could you please work on fixing this?

@MehdiMirakhorli I just want to make sure you are aware of this bug still existing in SAIN.

**Comment by jgarci40** [comment]
@khoiminhpham @Ibrahimvse What's the status of this, guys?
@TarandeepSingh562

**Comment by Ibrahimvse** [comment]
fixed
