### ISSUE TITLE
Inability to Click URL Links Under "Sain Faqs"

### ISSUE THREAD

**Issue by TarandeepSingh562** [SAIN-Project/Frontend#33]
While browsing under "Sain Faqs" on the main website, I found a slight issue where URLs are not clickable and have to be manually copied over to a new tab to be opened. I have attached some images to visually show the issue. 

![image](https://user-images.githubusercontent.com/85138366/133151683-dff05946-6d3e-4d16-8bbe-17a52eca3257.png)
![image](https://user-images.githubusercontent.com/85138366/133151731-94eec10d-4eff-4338-8a0a-5507a82f68fb.png)
![image](https://user-images.githubusercontent.com/85138366/133151747-c0333a6e-faac-48f4-881f-aa24c607f5e4.png)
![image](https://user-images.githubusercontent.com/85138366/133151757-bba4b85a-1382-4a81-be71-4e49c7380bbb.png)

**Comment by jgarci40** [comment]
@khoiminhpham @Ibrahimvse What's the status of this, guys?
@TarandeepSingh562

**Comment by Ibrahimvse** [comment]
fixed

**Comment by khoiminhpham** [comment]
![image](https://user-images.githubusercontent.com/47465932/160974971-42345830-e871-4801-9f6a-09e2e9647b40.png)

It's still showing html to me, you may want to double check this Ibrahim. Thanks,

**Comment by Ibrahimvse** [comment]
![image](https://user-images.githubusercontent.com/62664749/160975283-659af689-761d-4257-b173-234fcc69938e.png)

**Comment by Ibrahimvse** [comment]
Khoi I think you need to clear your browser cache

**Comment by khoiminhpham** [comment]
Could be my browser, thanks for your verification, Ibrahim.
